-- BASELINE migration — DEC-052 Part 2, MILESTONE-006 Checkpoint B.
--
-- 🔴 THIS MIGRATION WAS NEVER EXECUTED BY PRISMA.
-- The `session` table is created and owned by connect-pg-simple's own
-- table.sql, which was applied directly. This file exists so that Prisma's
-- migration history matches the database and `prisma migrate dev` reports no
-- drift. It was recorded with:
--
--     prisma migrate resolve --applied 20260810000000_baseline_connect_pg_simple_session
--
-- 🔴 Do NOT run `prisma migrate reset` to "fix" a drift complaint here.
-- vitashop_dev is a live, seeded database.
--
-- The SQL below is the Prisma-canonical rendering of connect-pg-simple's DDL
-- (generated by `prisma migrate diff`); it matches the live table's columns,
-- primary key `session_pkey` and index `IDX_session_expire`.

-- CreateTable
CREATE TABLE "session" (
    "sid" VARCHAR NOT NULL,
    "sess" JSON NOT NULL,
    "expire" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("sid")
);

-- CreateIndex
CREATE INDEX "IDX_session_expire" ON "session"("expire");

